package com.tapalque.gastronomia.demo.enu;

/**
 * Enum SUPER COMPLETO con ingredientes comunes para facilitar la selección en el frontend
 * con búsqueda y autocomplete (debounce)
 *
 * Incluye 200+ ingredientes organizados por categorías
 */
public enum CommonIngredientEnum {

    // ==================== CARNES Y AVES ====================
    CARNE_VACUNA("Carne vacuna"),
    CARNE_CERDO("Carne de cerdo"),
    CARNE_CORDERO("Carne de cordero"),
    CARNE_TERNERA("Carne de ternera"),
    BIFE_CHORIZO("Bife de chorizo"),
    LOMO("Lomo"),
    VACIO("Vacío"),
    ASADO("Asado"),
    COSTILLA("Costilla"),
    OSOBUCO("Osobuco"),
    CARNE_PICADA("Carne picada"),
    POLLO("Pollo"),
    PECHUGA_POLLO("Pechuga de pollo"),
    PATA_MUSLO_POLLO("Pata muslo de pollo"),
    ALITAS_POLLO("Alitas de pollo"),
    PAVO("Pavo"),
    PATO("Pato"),
    CODORNIZ("Codorniz"),
    CONEJO("Conejo"),

    // ==================== PESCADOS Y MARISCOS ====================
    PESCADO("Pescado"),
    SALMON("Salmón"),
    ATUN("Atún"),
    MERLUZA("Merluza"),
    CORVINA("Corvina"),
    TRUCHA("Trucha"),
    PEJERREY("Pejerrey"),
    LANGOSTINO("Langostino"),
    CAMARON("Camarón"),
    CALAMAR("Calamar"),
    PULPO("Pulpo"),
    MEJILLON("Mejillón"),
    ALMEJA("Almeja"),
    VIEIRA("Vieira"),
    CENTOLLA("Centolla"),
    CANGREJO("Cangrejo"),

    // ==================== FIAMBRES Y EMBUTIDOS ====================
    JAMON("Jamón"),
    JAMON_CRUDO("Jamón crudo"),
    JAMON_COCIDO("Jamón cocido"),
    SALAME("Salame"),
    SALAMIN("Salamín"),
    MORTADELA("Mortadela"),
    BACON("Bacon"),
    PANCETA("Panceta"),
    CHORIZO("Chorizo"),
    SALCHICHA("Salchicha"),
    MORCILLA("Morcilla"),
    LONGANIZA("Longaniza"),
    BONDIOLA("Bondiola"),

    // ==================== VEGETALES ====================
    TOMATE("Tomate"),
    TOMATE_CHERRY("Tomate cherry"),
    TOMATE_PERITA("Tomate perita"),
    LECHUGA("Lechuga"),
    LECHUGA_CRIOLLA("Lechuga criolla"),
    LECHUGA_MORADA("Lechuga morada"),
    LECHUGA_MANTECOSA("Lechuga mantecosa"),
    CEBOLLA("Cebolla"),
    CEBOLLA_MORADA("Cebolla morada"),
    CEBOLLA_VERDEO("Cebolla de verdeo"),
    PUERRO("Puerro"),
    AJO("Ajo"),
    PAPA("Papa"),
    BATATA("Batata"),
    ZANAHORIA("Zanahoria"),
    PIMIENTO("Pimiento"),
    PIMIENTO_ROJO("Pimiento rojo"),
    PIMIENTO_VERDE("Pimiento verde"),
    PIMIENTO_AMARILLO("Pimiento amarillo"),
    MORRÓN("Morrón"),
    AJI("Ají"),
    AJI_PICANTE("Ají picante"),
    AJI_VINAGRE("Ají en vinagre"),
    CHAMPINON("Champiñón"),
    HONGOS("Hongos"),
    HONGOS_PORTOBELLO("Hongos portobello"),
    ACEITUNAS("Aceitunas"),
    ACEITUNAS_NEGRAS("Aceitunas negras"),
    ACEITUNAS_VERDES("Aceitunas verdes"),
    PEPINO("Pepino"),
    PEPINILLO("Pepinillo"),
    REMOLACHA("Remolacha"),
    RABANITO("Rabanito"),
    BROCOLI("Brócoli"),
    COLIFLOR("Coliflor"),
    ESPINACA("Espinaca"),
    ACELGA("Acelga"),
    RUCULA("Rúcula"),
    RADICHETA("Radicheta"),
    ESCAROLA("Escarola"),
    REPOLLO("Repollo"),
    REPOLLO_MORADO("Repollo morado"),
    ZAPALLITO("Zapallito"),
    ZAPALLO("Zapallo"),
    CALABAZA("Calabaza"),
    BERENJENA("Berenjena"),
    MAIZ("Maíz"),
    CHOCLO("Choclo"),
    ARVEJAS("Arvejas"),
    LENTEJAS("Lentejas"),
    GARBANZOS("Garbanzos"),
    POROTOS("Porotos"),
    POROTOS_NEGROS("Porotos negros"),
    HABAS("Habas"),
    SOJA("Soja"),
    APIO("Apio"),
    ALCACHOFA("Alcachofa"),
    ESPARRAGO("Espárrago"),
    PALTA("Palta"),
    AGUACATE("Aguacate"),
    JENGIBRE("Jengibre"),

    // ==================== QUESOS Y LÁCTEOS ====================
    QUESO_MOZZARELLA("Queso mozzarella"),
    QUESO_PARMESANO("Queso parmesano"),
    QUESO_REGGIANITO("Queso reggianito"),
    QUESO_CHEDDAR("Queso cheddar"),
    QUESO_ROQUEFORT("Queso roquefort"),
    QUESO_AZUL("Queso azul"),
    QUESO_BRIE("Queso brie"),
    QUESO_CAMEMBERT("Queso camembert"),
    QUESO_GOUDA("Queso gouda"),
    QUESO_PROVOLONE("Queso provolone"),
    QUESO_SARDO("Queso sardo"),
    QUESO_FONTINA("Queso fontina"),
    QUESO_GRUYERE("Queso gruyere"),
    QUESO_CREMA("Queso crema"),
    QUESO_MASCARPONE("Queso mascarpone"),
    QUESO_PORT_SALUT("Queso port salut"),
    QUESO_MANTECOSO("Queso mantecoso"),
    QUESO_PATEGRÁS("Queso pategrás"),
    RICOTA("Ricota"),
    CREMA("Crema"),
    CREMA_ACIDA("Crema ácida"),
    LECHE("Leche"),
    LECHE_DESCREMADA("Leche descremada"),
    LECHE_ENTERA("Leche entera"),
    LECHE_CONDENSADA("Leche condensada"),
    MANTECA("Manteca"),
    MARGARINA("Margarina"),
    YOGUR("Yogur"),
    YOGUR_GRIEGO("Yogur griego"),
    DULCE_LECHE("Dulce de leche"),

    // ==================== HUEVOS ====================
    HUEVO("Huevo"),
    CLARA_HUEVO("Clara de huevo"),
    YEMA_HUEVO("Yema de huevo"),

    // ==================== MASAS Y HARINAS ====================
    HARINA("Harina"),
    HARINA_0000("Harina 0000"),
    HARINA_INTEGRAL("Harina integral"),
    HARINA_MAIZ("Harina de maíz"),
    HARINA_TRIGO("Harina de trigo"),
    POLENTA("Polenta"),
    SEMOLA("Sémola"),
    MASA_PIZZA("Masa de pizza"),
    MASA_EMPANADA("Masa de empanada"),
    MASA_HOJALDRE("Masa de hojaldre"),
    MASA_FILO("Masa filo"),
    PAN("Pan"),
    PAN_RALLADO("Pan rallado"),
    PAN_LACTAL("Pan lactal"),
    PAN_FRANCES("Pan francés"),
    PAN_PITA("Pan pita"),
    PAN_INTEGRAL("Pan integral"),
    TOSTADAS("Tostadas"),
    GALLETAS("Galletas"),
    GALLETITAS_DULCES("Galletitas dulces"),
    GALLETITAS_SALADAS("Galletitas saladas"),

    // ==================== PASTAS ====================
    FIDEOS("Fideos"),
    SPAGHETTI("Spaghetti"),
    TALLARINES("Tallarines"),
    FETUCCINI("Fetuccini"),
    RAVIOLES("Ravioles"),
    SORRENTINOS("Sorrentinos"),
    CAPELETIS("Capeletis"),
    ÑOQUIS("Ñoquis"),
    LASAGNA("Lasagna"),
    CANELONES("Canelones"),
    PASTA_RELLENA("Pasta rellena"),

    // ==================== ARROCES Y GRANOS ====================
    ARROZ("Arroz"),
    ARROZ_BLANCO("Arroz blanco"),
    ARROZ_INTEGRAL("Arroz integral"),
    ARROZ_YAMANÍ("Arroz yamaní"),
    QUINOA("Quinoa"),
    COUS_COUS("Cous cous"),
    BULGUR("Bulgur"),
    AVENA("Avena"),
    CHIA("Chía"),
    LINO("Lino"),

    // ==================== SALSAS Y CONDIMENTOS ====================
    SALSA_TOMATE("Salsa de tomate"),
    SALSA_BLANCA("Salsa blanca"),
    SALSA_BECHAMEL("Salsa bechamel"),
    SALSA_GOLF("Salsa golf"),
    SALSA_CESAR("Salsa césar"),
    SALSA_CRIOLLA("Salsa criolla"),
    SALSA_SOJA("Salsa de soja"),
    SALSA_BARBACOA("Salsa barbacoa"),
    SALSA_INGLESA("Salsa inglesa"),
    SALSA_TERIYAKI("Salsa teriyaki"),
    SALSA_TABASCO("Salsa tabasco"),
    SALSA_PESTO("Salsa pesto"),
    MAYONESA("Mayonesa"),
    MOSTAZA("Mostaza"),
    MOSTAZA_DIJON("Mostaza dijon"),
    KETCHUP("Ketchup"),
    VINAGRE("Vinagre"),
    VINAGRE_BALSAMICO("Vinagre balsámico"),
    ACETO("Aceto balsámico"),
    ACEITE_OLIVA("Aceite de oliva"),
    ACEITE_GIRASOL("Aceite de girasol"),
    ACEITE_MAIZ("Aceite de maíz"),
    SAL("Sal"),
    SAL_GRUESA("Sal gruesa"),
    SAL_MARINA("Sal marina"),
    PIMIENTA("Pimienta"),
    PIMIENTA_NEGRA("Pimienta negra"),
    PIMIENTA_BLANCA("Pimienta blanca"),
    PIMIENTA_ROSA("Pimienta rosa"),
    OREGANO("Orégano"),
    ALBAHACA("Albahaca"),
    PEREJIL("Perejil"),
    CILANTRO("Cilantro"),
    ROMERO("Romero"),
    TOMILLO("Tomillo"),
    LAUREL("Laurel"),
    MENTA("Menta"),
    ESTRAGÓN("Estragón"),
    ENELDO("Eneldo"),
    AJI_MOLIDO("Ají molido"),
    PAPRIKA("Páprika"),
    PIMENTON("Pimentón"),
    COMINO("Comino"),
    CURRY("Curry"),
    CURCUMA("Cúrcuma"),
    NUEZ_MOSCADA("Nuez moscada"),
    CANELA("Canela"),
    CLAVO_OLOR("Clavo de olor"),
    AZAFRAN("Azafrán"),
    VAINILLA("Vainilla"),
    EXTRACTO_VAINILLA("Extracto de vainilla"),
    CALDO("Caldo"),
    CALDO_POLLO("Caldo de pollo"),
    CALDO_VERDURA("Caldo de verdura"),
    CALDO_CARNE("Caldo de carne"),
    CHIMICHURRI("Chimichurri"),
    PROVENZAL("Provenzal"),

    // ==================== FRUTAS ====================
    LIMON("Limón"),
    LIMA("Lima"),
    NARANJA("Naranja"),
    MANDARINA("Mandarina"),
    POMELO("Pomelo"),
    MANZANA("Manzana"),
    MANZANA_VERDE("Manzana verde"),
    MANZANA_ROJA("Manzana roja"),
    PERA("Pera"),
    BANANA("Banana"),
    PLATANO("Plátano"),
    FRUTILLA("Frutilla"),
    FRAMBUESA("Frambuesa"),
    MORA("Mora"),
    ARANDANO("Arándano"),
    CEREZA("Cereza"),
    DURAZNO("Durazno"),
    MELOCOTON("Melocotón"),
    DAMASCO("Damasco"),
    CIRUELA("Ciruela"),
    SANDIA("Sandía"),
    MELON("Melón"),
    KIWI("Kiwi"),
    ANANÁ("Ananá"),
    PIÑA("Piña"),
    MANGO("Mango"),
    PAPAYA("Papaya"),
    COCO("Coco"),
    PASA_UVA("Pasa de uva"),
    UVA("Uva"),
    HIGO("Higo"),

    // ==================== FRUTOS SECOS ====================
    NUEZ("Nuez"),
    NUEZ_PECAN("Nuez pecán"),
    ALMENDRA("Almendra"),
    AVELLANA("Avellana"),
    CASTAÑA("Castaña"),
    MANI("Maní"),
    PISTACHO("Pistacho"),
    ANACARDO("Anacardo"),
    SEMILLAS_GIRASOL("Semillas de girasol"),
    SEMILLAS_ZAPALLO("Semillas de zapallo"),

    // ==================== BEBIDAS ====================
    AGUA("Agua"),
    AGUA_MINERAL("Agua mineral"),
    AGUA_SABORIZADA("Agua saborizada"),
    GASEOSA("Gaseosa"),
    COCA_COLA("Coca Cola"),
    SPRITE("Sprite"),
    FANTA("Fanta"),
    PEPSI("Pepsi"),
    SEVEN_UP("Seven up"),
    CERVEZA("Cerveza"),
    CERVEZA_RUBIA("Cerveza rubia"),
    CERVEZA_NEGRA("Cerveza negra"),
    CERVEZA_ROJA("Cerveza roja"),
    VINO("Vino"),
    VINO_TINTO("Vino tinto"),
    VINO_BLANCO("Vino blanco"),
    VINO_ROSADO("Vino rosado"),
    CHAMPAGNE("Champagne"),
    SIDRA("Sidra"),
    FERNET("Fernet"),
    WHISKY("Whisky"),
    RON("Ron"),
    VODKA("Vodka"),
    GIN("Gin"),
    TEQUILA("Tequila"),
    LICOR("Licor"),
    JUGO("Jugo"),
    JUGO_NARANJA("Jugo de naranja"),
    JUGO_MANZANA("Jugo de manzana"),
    JUGO_POMELO("Jugo de pomelo"),
    JUGO_DURAZNO("Jugo de durazno"),
    LIMONADA("Limonada"),
    CAFE("Café"),
    CAFE_ESPRESSO("Café espresso"),
    CAFE_LATTE("Café latte"),
    CAPPUCCINO("Cappuccino"),
    TE("Té"),
    TE_NEGRO("Té negro"),
    TE_VERDE("Té verde"),
    TE_ROJO("Té rojo"),
    MATE("Mate"),
    MATE_COCIDO("Mate cocido"),
    CHOCOLATE_CALIENTE("Chocolate caliente"),
    LICUADO("Licuado"),
    SMOOTHIE("Smoothie"),

    // ==================== DULCES Y POSTRES ====================
    AZUCAR("Azúcar"),
    AZUCAR_NEGRA("Azúcar negra"),
    AZUCAR_IMPALPABLE("Azúcar impalpable"),
    EDULCORANTE("Edulcorante"),
    MIEL("Miel"),
    MERMELADA("Mermelada"),
    JALEA("Jalea"),
    CHOCOLATE("Chocolate"),
    CHOCOLATE_AMARGO("Chocolate amargo"),
    CHOCOLATE_BLANCO("Chocolate blanco"),
    CHOCOLATE_CON_LECHE("Chocolate con leche"),
    CACAO("Cacao"),
    NUTELLA("Nutella"),
    HELADO("Helado"),
    HELADO_VAINILLA("Helado de vainilla"),
    HELADO_CHOCOLATE("Helado de chocolate"),
    HELADO_DULCE_LECHE("Helado de dulce de leche"),
    HELADO_FRUTILLA("Helado de frutilla"),
    CREMA_CHANTILLY("Crema chantilly"),
    CREMA_PASTELERA("Crema pastelera"),
    FLAN("Flan"),
    GELATINA("Gelatina"),
    MOUSSE("Mousse"),
    TIRAMISU("Tiramisú"),
    PANQUEQUE("Panqueque"),

    // ==================== OTROS ====================
    PICANTE("Picante"),
    LEVADURA("Levadura"),
    POLVO_HORNEAR("Polvo de hornear"),
    BICARBONATO("Bicarbonato"),
    MAICENA("Maicena"),
    ALMIDON_MAIZ("Almidón de maíz"),
    ESENCIA("Esencia"),
    COLORANTE("Colorante"),
    COCO_RALLADO("Coco rallado");

    private final String displayName;

    CommonIngredientEnum(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }

    /**
     * Busca ingredientes que contengan el término de búsqueda (case insensitive)
     * Útil para implementar búsqueda con debounce en el frontend
     */
    public static java.util.List<CommonIngredientEnum> search(String query) {
        if (query == null || query.trim().isEmpty()) {
            return java.util.Arrays.asList(values());
        }

        String lowerQuery = query.toLowerCase();
        return java.util.Arrays.stream(values())
            .filter(ingredient -> ingredient.displayName.toLowerCase().contains(lowerQuery))
            .collect(java.util.stream.Collectors.toList());
    }

    /**
     * Obtiene todos los ingredientes como lista de strings
     */
    public static java.util.List<String> getAllIngredientNames() {
        return java.util.Arrays.stream(values())
            .map(CommonIngredientEnum::getDisplayName)
            .collect(java.util.stream.Collectors.toList());
    }
}
