

services:
  # ==========================================
  # INFRAESTRUCTURA
  # ==========================================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672" # Panel de gestión
      - "5672:5672"   # Comunicación interna
    networks:
      - tapalque-net

  # Bases de datos Mongo
  pedidos-db:
    image: mongo:latest
    container_name: pedidos-db
    ports:
      - "27017:27017"
    volumes:
      - pedidos_data:/data/db
      - ./init-scripts/mongo/init-pedidos.js:/docker-entrypoint-initdb.d/init-pedidos.js:ro
    networks:
      - tapalque-net

  reservas-db:
    image: mongo:latest
    container_name: reservas-db
    ports:
      - "27018:27017"
    volumes:
      - reservas_data:/data/db
      - ./init-scripts/mongo/init-reservas.js:/docker-entrypoint-initdb.d/init-reservas.js:ro
    networks:
      - tapalque-net

  # Bases de datos MySQL
  gastronomia-db:
    image: mysql:8
    container_name: gastronomia-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gastronomia
    ports:
      - "3305:3306"
    volumes:
      - gastronomia_data:/var/lib/mysql
      - ./init-scripts/mysql/init-gastronomia.sql:/docker-entrypoint-initdb.d/init-gastronomia.sql:ro
    networks:
      - tapalque-net

  hosteleria-db:
    image: mysql:8
    container_name: hosteleria-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hosteleria
    ports:
      - "3307:3306"
    volumes:
      - hosteleria_data:/var/lib/mysql
      - ./init-scripts/mysql/init-hosteleria.sql:/docker-entrypoint-initdb.d/init-hosteleria.sql:ro
    networks:
      - tapalque-net

  mercado-pago-db:
    image: mysql:8
    container_name: mercado-pago-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mercado_pago
    ports:
      - "3308:3306"
    volumes:
      - mercado_pago_data:/var/lib/mysql
      - ./init-scripts/mysql/init-mercado-pago.sql:/docker-entrypoint-initdb.d/init-mercado-pago.sql:ro
    networks:
      - tapalque-net

  jwt-db:
    image: mysql:8
    container_name: jwt-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jwt
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - jwt_data:/var/lib/mysql
      - ./init-scripts/mysql/init-jwt.sql:/docker-entrypoint-initdb.d/init-jwt.sql:ro
    networks:
      - tapalque-net

  user-db:
    image: mysql:8
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
    ports:
      - "3310:3306"
    volumes:
      - user_data:/var/lib/mysql
      - ./init-scripts/mysql/init-user.sql:/docker-entrypoint-initdb.d/init-user.sql:ro
    networks:
      - tapalque-net

  comercio-db:
    image: mysql:8
    container_name: comercio-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comercio
    ports:
      - "3311:3306"
    volumes:
      - comercio_data:/var/lib/mysql
      - ./init-scripts/mysql/init-comercio.sql:/docker-entrypoint-initdb.d/init-comercio.sql:ro
    networks:
      - tapalque-net

  # ==========================================
  # MICROSERVICIOS
  # ==========================================
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka/apps" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_interval: 20s
    restart: always
    networks:
      - tapalque-net

  msvc-gateway-server:
    build: ./msvc-gateway-server
    container_name: msvc-gateway-server
    depends_on:
      - eureka-server
    ports:
      - "8090:8090"
    restart: always
    networks:
      - tapalque-net

  msvc-jwt:
    build: ./msvc-jwt
    container_name: msvc-jwt
    depends_on:
      jwt-db: 
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    restart: always
    networks:
      - tapalque-net

  msvc-user:
    build: ./msvc-user
    container_name: msvc-user
    depends_on:
      - user-db
      - eureka-server
    restart: always
    networks:
      - tapalque-net

  msvc-pedidos:
    build: ./msvc-pedidos
    container_name: msvc-pedidos
    depends_on:
      - pedidos-db
      - rabbitmq
      - eureka-server
    restart: always
    networks:
      - tapalque-net

  msvc-reservas:
    build: ./msvc-reservas
    container_name: msvc-reservas
    depends_on:
      - reservas-db
      - rabbitmq
      - eureka-server
    restart: always
    networks:
      - tapalque-net

  msvc-gastronomia:
    build: ./msvc-gastronomia
    container_name: msvc-gastronomia
    depends_on:
      - gastronomia-db
      - eureka-server
    restart: always
    networks:
      - tapalque-net

  msvc-hosteleria:
    build: ./msvc-hosteleria
    container_name: msvc-hosteleria
    depends_on:
      - hosteleria-db
      - eureka-server
    restart: always
    networks:
      - tapalque-net

  msvc-mercado-pago:
    build: ./msvc-mercado-pago
    container_name: msvc-mercado-pago
    depends_on:
      - mercado-pago-db
      - rabbitmq
      - eureka-server
    restart: always
    networks:
      - tapalque-net

  msvc-comercio:
    build: ./msvc-comercio
    container_name: msvc-comercio
    depends_on:
      - comercio-db
      - eureka-server
    restart: always
    networks:
      - tapalque-net

# ==========================================
# VOLUMENES Y REDES
# ==========================================
volumes:
  pedidos_data:
  reservas_data:
  gastronomia_data:
  hosteleria_data:
  mercado_pago_data:
  jwt_data:
  user_data:
  comercio_data:

networks:
  tapalque-net:
    driver: bridge
