spring.application.name=msvc-gateway-server
server.port=8090

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
# Frontend URL (para CORS)
app.frontend-url=${APP_FRONTEND_URL:http://localhost:3000}
# Logging
logging.level.root=WARN
logging.level.org.springframework.web=INFO
logging.level.org.springframework.cloud.gateway=DEBUG

